name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - run: npm ci
    - run: npm run build --if-present

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}  # Ensure you set this in your repo secrets
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}  # Ensure you set this in your repo secrets
      run: |
        # Start SSH agent and add your SSH key
        eval "$(ssh-agent -s)"
        echo "${EC2_SSH_KEY}" | tr -d '\r' | ssh-add -
        
        # SSH into EC2 and deploy changes
        ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST << 'EOF'
          cd CI-CD_TESTING/ || exit
          git pull origin master  # Ensure you are pulling from the correct branch
          npm install              # Install any new dependencies
          pm2 restart server.js    # Restart your application
        EOF
